package com.timberta.walletleaks.presentation.ui.fragments.authentication

import com.timberta.walletleaks.presentation.base.BaseViewModel

class SignInViewModel : BaseViewModel() {

    val passwordList = arrayListOf(
        "QPY7HEjYrr3KXJ6D",
        "30t9NhYOtWXcfuUX",
        "XfrkKVbSXR2NuonL",
        "JuiGPLVngyJsHM8u",
        "EBBvITQH4w0vcCnB",
        "7E1zsW25pJB0ef1h",
        "zFW10JgXp48OaVea",
        "rx1csqgsHdECnRSJ",
        "h4fvT2GuJNlZt2QQ",
        "TLNAboYZzm5bwPR9",
        "AI3szYJxkTmsR6Mh",
        "0zzY1RdCR8WPrwDv",
        "CkzDq0SfI9ayUbvs",
        "ahIECoC5FiGoTI5i",
        "gxgCfX97yLsM0nT7",
        "4fiUgyX5xDrfsYSY",
        "GbuH1OgZ16vOOKgp",
        "jd4hFJqSQdqXQVkM",
        "X1LgpL5AussWEbEo",
        "folPpqmshPVLASIv",
        "yAkbpBfitbq452AV",
        "5PqJ0ajwDXJyKP76",
        "D7atV4zFEjXYz2Yk",
        "W7AA0t6hntYGxeRs",
        "1T2MaTtPaX1bbfXN",
        "DKjBwiMxHcpZxVHn",
        "lxnZWENBMHXV9yhb",
        "ommIbM4jlaZRFdHB",
        "BJayDLIXMt1eAA4g",
        "Ml0rrJ4DnWu9k26u",
        "JQwuNIjkp3EmsZ2k",
        "uhqHwo4z8XCIGXwU",
        "kMh6otzTa0Jyr5kN",
        "hAy9kcWIe4mK5foM",
        "oeUdzFdqOGSP9iu9",
        "32Nwmed2JMmUweTb",
        "ukvKh5Jm8nXWtH7K",
        "NBcZYkV4NaSDPcyD",
        "sf7eLSRaO8sGGXvH",
        "8Xf8j6mqnIqVnm8j",
        "GM9THDTyRAplvzt6",
        "D5gik2FSeujHSLQ1",
        "wSuiXMKGItjOYSE7",
        "4gSolAHGeEJ724I5",
        "yxmds46J75k9az8O",
        "a3k0HsJ76uzBrVbX",
        "pmEJzIgRUqsHQzSa",
        "ED35dgyCZ5StjPlI",
        "CbIR2vNfgtLCJj9W",
        "1Y9TedcPIKGmXr46",
        "l0Syw93yJaiUJd6c"
    )
}